version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:21.0.1
    hostname: keycloak-server
    ports:
      - "8080:8080"

    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak

    networks:
      - ${GLOBAL_NETWORK:-elastic}



