version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:21.0.1
    hostname: keycloak-server
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - start-dev
      - --features admin-fine-grained-authz
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      DB_VENDOR: POSTGRES
      DB_ADDR: host.docker.internal
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: keycloak
      DB_PASSWORD: keycloak

