server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tronglv92/config-server-repository
          default-label: master
          username: tronglv92
          password: '{cipher}5d2d9f667be7a4864767ca0fe4978f249e70c6653464f6b5696c393d9413b10f7dacf8d7cdf48beeec1f79fedfd8e709a1a277968e0057a835409beda6446ac9'
          clone-on-start: true
          timeout: 10
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
#      password: ENC(hqrPRmgHkBPxQApK2puH3P18YkcztloaJwZdablBCm3j0xlIhNbxPazHnesKuoT2chroWJmeTElgi/daGRLtIw==)
      password: '{cipher}c77402cd0f6946c5e71c2f21a2218d42896543bd472d9f1d2a6e63f5c70f65e256e0801929199404d0195606cea4bfa6'
encrypt:
  key: 'Demo_Pwd!2020'
